// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPing = `-- name: InsertPing :exec
insert into ping_log (message) values ($1)
`

func (q *Queries) InsertPing(ctx context.Context, message string) error {
	_, err := q.db.Exec(ctx, insertPing, message)
	return err
}

const pingStats = `-- name: PingStats :one
select count(*)::bigint as ping_count, now()::timestamptz as db_time from ping_log
`

type PingStatsRow struct {
	PingCount int64
	DbTime    pgtype.Timestamptz
}

func (q *Queries) PingStats(ctx context.Context) (PingStatsRow, error) {
	row := q.db.QueryRow(ctx, pingStats)
	var i PingStatsRow
	err := row.Scan(&i.PingCount, &i.DbTime)
	return i, err
}
